language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly-2017-07-25
      before_script:
      - cargo install clippy --vers 0.0.145
      - cargo install rustfmt --vers 0.9.0
      script:
      - cargo clippy -- -D warnings
      - cargo fmt -- --write-mode diff
