[package]
name = "swagger"
version = "0.1.0"
authors = ["Robin McCorkell <robin.mccorkell@metaswitch.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hyper = "0.10"
base64 = "0.5"
iron = "0.5"
